### ISSUE TITLE
Built directories can't be moved across filesystems

### ISSUE THREAD

**Issue by valeth** [crenv/crystal-build#66]
## Issue
If the `CRYSTAL_BUILD_CACHE_PATH` is set to a location outside of the filesystem where `CRENV_ROOT` is located the move will fail.

Apparently the `rename` function doesn't support moves between filesystems.

## Potential fix
Other options seem to be the [`File::Copy::Recursive`](http://search.cpan.org/~dmuey/File-Copy-Recursive/) module.
I would try and fix it myself, but I don't know anything about Perl.

## Error message
With `CRYSTAL_BUILD_CACHE_PATH` set to `/tmp/crystal-build`
```
...
Moving the Crystal directory ...faild to move the Crystal directory Invalid cross-device link
```

**Comment by taylorthurlow** [comment]
I'm going to close this one because it's just not going to get fixed in this project. There's [a ticket open](https://github.com/crenv/crystal-build-cr/issues/9) in the rewrite repo for supporting the `CRYSTAL_BUILD_CACHE_PATH` variable, and once that's implemented we can evaluate whether or not this is still an issue, but I don't expect Crystal's filesystem libraries to not support cross-filesystem transfers. I've left myself a note in the linked issue to check cross-filesystem support.
